[project]
name = "signwriting-transcription"
description = "Transcribe single signs into SignWriting"
version = "0.0.1"
authors = [
    { name = "Amit Moryossef", email = "amit@sign.mt" },
]
readme = "README.md"
dependencies = [
    "tqdm",
    "pandas",
    # Loading and processing poses
    "pose-format",
    "mediapipe",
    # SignWriting essentials
    "signwriting @ git+https://github.com/sign-language-processing/signwriting",
    "signwriting-evaluation @ git+https://github.com/sign-language-processing/signwriting-evaluation",
    # Pose segmentation for data augmentation & cli tools
    "sign_language_segmentation @ git+https://github.com/sign-language-processing/segmentation",
    # Modeling
    "multimodalhugs @ git+https://github.com/GerrySant/multimodalhugs",
    # CLI
    "pympi-ling", # Used for reading and writing ELAN files
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pylint",
    "ruff"
]

[tool.yapf]
based_on_style = "google"
column_limit = 120

[tool.pylint]
max-line-length = 120
disable = [
    "C0114", # Missing module docstring
    "C0115", # Missing class docstring
    "C0116", # Missing function or method docstring
]
good-names = ["ms"]

[tool.setuptools]
packages = [
    "signwriting_transcription",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings  
    "F",    # pyflakes
    "C90",  # mccabe complexity
    "I",    # isort
    "N",    # pep8-naming
    "UP",   # pyupgrade
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "PT",   # flake8-pytest-style
    "W605", # invalid escape sequence
    "BLE",  # flake8-blind-except
    "TRY",  # tryceratops
]

[tool.pytest.ini_options]
addopts = "-v"
testpaths = ["signwriting_transcription"]

# TODO: Add a script to run the inference
[project.scripts]
pose_to_signwriting = "signwriting_transcription.pose_to_signwriting.bin:main"
