[project]
name = "signwriting-transcription"
description = "Transcribe single signs into SignWriting"
version = "0.0.1"
authors = [
    { name = "Amit Moryossef", email = "amit@sign.mt" },
    { name = "Rotem Zolbermn", email = "rotemzil2203@gmail.com" },
    { name = "Ohad Langer", email = "ohadlanger1@gmail.com" }
]
readme = "README.md"
dependencies = [
    "tqdm",
    "pandas",
    # Loading and processing poses
    "pose-format",
    "mediapipe",
    # SignWriting essentials
    "signwriting @ git+https://github.com/sign-language-processing/signwriting",
    "signwriting-evaluation @ git+https://github.com/sign-language-processing/signwriting-evaluation",
    # Pose segmentation for data augmentation & cli tools
    "sign_language_segmentation @ git+https://github.com/sign-language-processing/segmentation",
    # Modeling
    "multimodalhugs @ git+https://github.com/GerrySant/multimodalhugs",
    # CLI
    "pympi-ling", # Used for reading and writing ELAN files
]

dev = [
    "pytest",
    "pylint"
]

[tool.yapf]
based_on_style = "google"
column_limit = 120

[tool.pylint]
max-line-length = 120
disable = [
    "C0114", # Missing module docstring
    "C0115", # Missing class docstring
    "C0116", # Missing function or method docstring
]
good-names = ["ms"]

[tool.setuptools]
packages = [
    "signwriting_transcription",
]

[tool.pytest.ini_options]
addopts = "-v"
testpaths = ["signwriting_transcription"]

[project.scripts]
pose_to_signwriting = "signwriting_transcription.pose_to_signwriting.bin:main"
