name: Test


on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Requirements
        run: pip install ".[dev]"

      - name: Test Code
        run: pytest .
